name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repo
        uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Upload Mod DLL
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.PROJECT_NAME }}.dll
          path: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.dll


      - name: Release
        uses: softprops/action-gh-release@v1
        if: start sWith(github.ref, 'refs/tags/')
        with:
            files: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.dll
            body_path: ${{ env.PROJECT_NAME }}/LATEST.md
            fail_on_unmatched_files: true