name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
      
jobs:
  call-submodulebuild:
    permissions:
      contents: write
    uses: AbyssMod/Abyss/.github/workflows/submodulebuild.yml@main
